routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth', 'verified']], function (){
    /*
     *  АДМИНСКАЯ ЧАСТЬ
     */
        Route::get('/update_conferences', 'ParserController@updateConferences');

    /*
     *  КЛИЕНТСКАЯ ЧАСТЬ
     */
        // Домашняя страниица
        Route::get('/', 'HomeController@index')->name('home');

        // Поиск
        Route::post('/globalsearch', 'SearchController@globalSearch');

        // Статьи
        Route::post('/publications/modal_show_publication', 'PublicationController@modalShowPublication');
        Route::post('/publications/apply_publication', 'PublicationController@applyPublication');
        Route::post('/publications/find_similar', 'PublicationController@findSimilar');
        Route::post('/publications/repost_list', 'PublicationController@repostList');
        Route::post('/publications/repost', 'PublicationController@repost');
        Route::post('/publications/cancel', 'PublicationController@cancel');
        Route::post('/publications/change_is_ready', 'PublicationController@changeIsReady');
        Route::post('/publications/change_is_literature', 'PublicationController@changeIsLiterature');
        Route::get('/publications_ready', 'PublicationController@indexReady')->name('publications_ready');
        Route::get('/publications_in_process', 'PublicationController@indexProcess')->name('publications_in_process')->middleware('user');
        Route::get('/publications_literature', 'PublicationController@indexLiterature')->name('publications_literature');
        Route::get('/publications/getreport', 'PublicationController@getPersonalReport');
        Route::post('/publications/createreport', 'PublicationController@CreatePersonalReport');
        Route::post('/publications/view', 'PublicationController@viewPublication');
        Route::post('/publications/change_is_edit', 'PublicationController@changeIsEdit');
        Route::resource('/publications', 'PublicationController');

        // НИР
        Route::post('/nir/modal_show_nir', 'NirController@modalShowNir');
        Route::post('/nir/apply_nir', 'NirController@applyNir');
        Route::post('/nir/find_similar', 'NirController@findSimilar');
        Route::post('/nir/repost_list', 'NirController@repostList');
        Route::post('/nir/repost', 'NirController@repost');
        Route::post('/nir/cancel', 'NirController@cancel');
        Route::post('/nir/edit', 'NirController@editNir');
        Route::post('/nir/view', 'NirController@viewNir');
        Route::post('/nir/destroy', 'NirController@destroyNir');
        Route::post('/nir/change_is_edit', 'NirController@changeIsEdit');
        Route::resource('/nir', 'NirController');

        // Конференции
        Route::get('/conference', 'ConferenceController@index')->name('conference')->middleware('user');

        // Профиль
        Route::post('/profile/createreport', 'ProfileController@CreateReport');
        Route::get('/profile/getreport', 'ProfileController@getReport');
        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::post('/profile/edit_profile', 'ProfileController@editProfileInfo');
        Route::post('/profile/save', 'ProfileController@updateProfileInfo');
        Route::post('/profile/save_pass', 'ProfileController@updatePassword');
        Route::post('/profile/gel_all_nirs', 'ProfileController@getAllNirs');
        Route::get('/profile/{id}', 'ProfileController@show')->name('userprofile');

        // Уведомления о статьях
        Route::post('/notifications/get', 'NotificationController@getNotifications');
        Route::post('/notifications/modal_show_alert', 'NotificationController@modalShowAlert');
        Route::post('/notifications/apply', 'NotificationController@applyNotification');
        Route::post('/notifications/cancel', 'NotificationController@cancelNotification');
        Route::post('/notifications/delete', 'NotificationController@deletePersonalNotifications');
});

resources/views/layouts/app.blade.php
<html lang="en">
{{--<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">--}}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Отчеты по НИР</title>

    <!-- Scripts -->
    {{--<script src="{{ asset('js/app.js') }}" defer></script>--}}

    <!-- Styles -->
    {{--<link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}

    <meta name="description" content="{{isset($description)}}" />
    <link rel="stylesheet" href="{{asset('modules/bootstrap/bootstrap.min.css')}}">
    <script src="{{asset('modules/jquery.min.js')}}"></script>
    <script src="{{asset('modules/popper.min.js')}}"></script>
    <script src="{{asset('modules/bootstrap/bootstrap.min.js')}}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="{{asset('modules/vue.js')}}"></script>
    <script src="{{asset('modules/lodash.min.js')}}"></script>
    <script src="{{asset('modules/dataTables.min.js')}}"></script>
    <link href="{{asset('modules/select2.min.css')}}" rel="stylesheet" />
    <link href="{{asset('modules/dataTables.min.css')}}" rel="stylesheet" />
    <script src="{{asset('modules/select2.min.js')}}"></script>
    <link rel="shortcut icon" href="{{asset('/img/icon.ico')}}" type="image/x-icon">
    <link href="{{asset('css/style.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('css/loader.css')}}" rel="stylesheet" type="text/css">
    <script src="{{asset('modules/autosize.min.js')}}"></script>
    <script src="{{asset('modules/datatables_sort.js')}}"></script>
    <script src="{{asset('modules/jquery.cookie.js')}}"></script>

    @auth
    <script>
        let count_alerts = {!! $countnotification !!}
    </script>
    @endauth
</head>
<body class=" <? if(isset($_COOKIE['theme'])) echo $_COOKIE['theme']; ?>">
    <sidebar>
        @auth
            <div class="name"><a href="{{route('profile')}}">{{ Auth::user()->fio_kir }} </a>
                <span class="count_alerts" id="count_alerts"></span>
                <script>
                    if (count_alerts != 0)
                        $('#count_alerts').html(count_alerts)
                    else
                        $('#count_alerts').hide()
                </script>
            </div>
        @endauth
        <ul class="menu">
            @guest
                <li>
                    <a href="{{ route('login') }}">Авторизация</a>
                </li>
                @if (Route::has('register'))
                    <li>
                        <a href="{{ route('register') }}">Регистрация</a>
                    </li>
                @endif
            @else
                <li><a href="{{route('nir.index')}}">Добавить НИР</a></li>
                @if (Auth::user()->status == 0 || Auth::user()->status == 1)
                <li><a href="{{route('publications_ready')}}">Мои статьи</a>
                    <ul>
                        <li><a href="{{route('publications_ready')}}">Готовые</a></li>
                        <li><a href="{{route('publications_in_process')}}">В разработке</a></li>
                        <li><a href="{{route('publications_literature')}}">Для литературы</a></li>
                    </ul>
                </li>
                @else
                    <li><a href="{{route('publications_ready')}}">Мои статьи</a></li>
                @endif
                @if (Auth::user()->status == 0 || Auth::user()->status == 1)
                <li><a href="{{route('conference')}}">Конференции</a></li>
                @endif
                <li><a href="{{route('profile')}}">Профиль</a></li>
                <li>
                    <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        Выйти
                    </a>
                </li>
                <li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            @endguest
        </ul>
    </sidebar>
    <header >
        <h1><a href="{{ route('home') }}">Отчеты по НИР</a></h1>
        <div>
            <button class="btn btn-light theme" onclick="check_theme();"><i class="fas fa-<?
                if(isset($_COOKIE['theme']))
                {
                    if ($_COOKIE['theme'] == 'dark') echo ('sun');
                        else echo ('moon');
                } else echo('moon'); ?>"></i></button>
            @auth
                <button class="btn btn-light help" data-toggle="collapse" href="#help"><i class="fa fa-info"></i></button>
                {{--<form action="">
                    <input type="text" class="search" placeholder="Поиск...">
                </form>--}}
            @endauth
        </div>
    </header>
    <content>
        <div class="collapse" id="help">
            <div class="info">
                <ul>
                    @foreach($types as $type)
                        <li><b>{{$type->id}}</b>. {{$type->title}}</li>
                    @endforeach
                </ul>
            </div>
        </div>
            <div class="row">
                <div class="col-md-12">
                    @if(session('status'))
                        <div class="alert alert-info">
                            {{session('status')}}
                        </div>
                    @endif
                </div>
            </div>
        @include('errors')
        @yield('content')
    </content>

    <script src="{{asset('js/scripts.js')}}"></script>
    <script src="{{asset('js/theme.js')}}"></script>

</body>
</html>